#!/usr/bin/env python3
"""Turn classifications into something a maintainer would actually read.

DRY RUN BY DEFAULT, AND THAT IS THE POINT.
A demo that can file issues against a real repository is one bug away from
spamming a project that explicitly asks people not to spam it. This module
prints markdown to stdout. Posting is a separate, deliberate step that a
maintainer would wire up after reviewing the output -- there is no --post flag
in the prototype.

    python3 -m flakeagent.report digest
    python3 -m flakeagent.report comment --run <id>
"""

import argparse
import json

from . import store

VERDICT_ICON = {
    "infra_blip": "🌐", "network_timeout": "⏱", "race_condition": "🏁",
    "resource_exhaustion": "💾", "real_bug": "🐛", "unknown": "❓",
}

ACTION = {
    "infra_blip": "Likely safe to re-run.",
    "network_timeout": "Likely safe to re-run; consider raising the timeout if frequent.",
    "race_condition": "Needs a fix, not a re-run. Re-running hides it.",
    "resource_exhaustion": "Check runner capacity before re-running.",
    "real_bug": "**Do not re-run.** This looks caused by the change under test.",
    "unknown": "Not classified with confidence — needs a human.",
}


def current(conn, limit):
    return conn.execute(
        """SELECT c.*, f.name, f.kind,
                  COUNT(DISTINCT j.run_id) AS runs
           FROM classifications c
           JOIN test_failures f ON f.fkey = c.fkey
           JOIN jobs j ON j.id = f.job_id
           WHERE c.valid_to IS NULL
           GROUP BY c.fkey
           ORDER BY runs DESC, c.confidence DESC
           LIMIT ?""",
        (limit,),
    ).fetchall()


def cmd_digest(conn, args):
    rows = current(conn, args.limit)
    if not rows:
        print("no classifications yet; run `python3 -m flakeagent.classify` first")
        return

    print("## Podman CI flake digest\n")
    print(f"_{len(rows)} distinct failing tests, most frequent first. "
          "Generated by podman-flake-agent (prototype)._\n")

    tin = sum(r["tokens_in"] or 0 for r in rows)
    tout = sum(r["tokens_out"] or 0 for r in rows)

    for r in rows:
        icon = VERDICT_ICON.get(r["category"], "•")
        dup = f" — likely duplicate of #{r['duplicate_of']}" if r["duplicate_of"] else ""
        print(f"### {icon} `{r['name'][:90]}`")
        print(f"**{r['category']}** (confidence {r['confidence']}) · "
              f"seen in {r['runs']} run(s) · {r['kind']}{dup}\n")
        print(f"{r['reasoning']}\n")

        evidence = json.loads(r["evidence"] or "[]")
        if evidence:
            print("Evidence:\n")
            print("```")
            for line in evidence[:6]:
                print(line)
            print("```\n")

        print(f"_{ACTION.get(r['category'], '')}_\n")
        for e in store.evidence_for(conn, r["fkey"]):
            print(f"- signal: `{e['signal']}` ({e['strength']}) — {e['detail']}")
        print()

    print("---")
    print(f"_Model input {tin:,} tokens, output {tout:,} tokens across {len(rows)} "
          "classifications._")


def cmd_comment(conn, args):
    rows = current(conn, args.limit)
    if not rows:
        print("no classifications yet")
        return

    flakes = [r for r in rows if r["category"] not in ("real_bug", "unknown")]
    real = [r for r in rows if r["category"] == "real_bug"]
    unsure = [r for r in rows if r["category"] == "unknown"]

    print("<!-- podman-flake-agent (prototype) — DRY RUN, not posted -->")
    print("**CI failure triage**\n")

    if real:
        print("⚠️ These look caused by this change, not by flakes:\n")
        for r in real:
            print(f"- `{r['name'][:80]}` — {r['reasoning'][:160]}")
        print()
    if flakes:
        print("These match known flake patterns and are probably safe to re-run:\n")
        for r in flakes:
            dup = f" (see #{r['duplicate_of']})" if r["duplicate_of"] else ""
            print(f"- `{r['name'][:80]}` — {r['category']}{dup}")
        print()
    if unsure:
        print(f"{len(unsure)} failure(s) could not be classified confidently "
              "and need a human.\n")

    print("_Automated triage. Verify before acting on it._")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["digest", "comment"])
    ap.add_argument("--limit", type=int, default=20)
    ap.add_argument("--db")
    ap.add_argument("--dry-run", action="store_true",
                    help="accepted for symmetry; output is always a dry run")
    args = ap.parse_args(argv)

    conn = store.connect(args.db)
    {"digest": cmd_digest, "comment": cmd_comment}[args.command](conn, args)
    conn.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
